const MESSAGE_STATUS = []
MESSAGE_STATUS['UNSEEN'] = 0
MESSAGE_STATUS['SEEN'] = 1

const ROOM_TYPE = []
ROOM_TYPE['PRIVATE'] = 0
ROOM_TYPE['GROUP'] = 1

const ENUM = {
  MESSAGE_STATUS,
  ROOM_TYPE
}

export default ENUM
